{
 "title": "cmpt756-g15-serverful-ml-app",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "description": "The average response time measured over 30 seconds intervals for successful requests. Shown per path.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\", method=\"POST\"}[30s]) / rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests under 5ms % ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{status=\"200\", le=\"0.005\", method=\"POST\"}[30s]) / ignoring(le) increase(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "description": "The memory usage of the Flask app. Based on data from the underlying Prometheus client library, not Flask specific.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"flask-api:8080\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\", method=\"POST\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}